### PR TITLE
Variable resistance selection

### PR DESCRIPTION
**Pull request by lufire**
Mainly updated [https://github.com/ZBT-Tools/pemfc-tkinter-app](https://github.com/ZBT-Tools/pemfc-tkinter-app) repository, however the following callback needed some temporary rework to be able to include the activation/deactivation logic of connected entries for the new dropdowns:

https://github.com/ZBT-Tools/pemfc-dash-app/blob/1a7ea57aed3d1c2984af530562491a225682804f/pemfc_dash/callbacks.py#L1376

### CODE REVIEW

**Comment by fkuschel** [comment]
image

Seems not to work

**Comment by lufire** [comment]
did you update your pemfc and pemfc_gui packages?

**Comment by fkuschel** [comment]
image
yes.

**Comment by fkuschel** [comment]
--> After restart of Pycharm it works.

**Review by fkuschel — APPROVED** [review]

**Pull request merged**
